git update xserver libxcb libxcb/xcb-proto xkeyboard-config mkfontscale libxtrans mesa plink until 21 June 2016
xserver          commit 111a045dcf0912dc5b178c18acda479b3972876b
libxcb           commit 65b298c7ca317d7e4316aa2b9e0499e13047c65c
libxcb/xcb-proto commit 95a262e0e66cd88b9d7a133917b3ba70ace77301
xkeyboard-config commit deb6293f48bd81e5a4110d09a0b30caf8e2a28d1
mkfontscale      commit ecb248d8865df376a97a795c2e4f58a3bf64c3f1
libxtrans        commit 3810e026323210df6ec6cf818f01832a63e9fbb9
mesa             commit b16d21270f9ea0173ebe059a3e82a4b451a80596
putty            commit 7b9ad090067e817321190fa3379264e6ee9d3b91

diff --git a/mesalib/src/Makefile.am b/mesalib/src/Makefile.am
--- a/mesalib/src/Makefile.am
+++ b/mesalib/src/Makefile.am
@@ -19,10 +19,47 @@
 # FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 # IN THE SOFTWARE.
 
+.PHONY: git_sha1.h.tmp
+git_sha1.h.tmp:
+	@# Don't assume that $(top_srcdir)/.git is a directory. It may be
+	@# a gitlink file if $(top_srcdir) is a submodule checkout or a linked
+	@# worktree.
+	@# If we are building from a release tarball copy the bundled header.
+	@if test -e $(top_srcdir)/.git; then \
+		if which git > /dev/null; then \
+		    git --git-dir=$(top_srcdir)/.git log -n 1 --oneline | \
+			sed 's/^\([^ ]*\) .*/#define MESA_GIT_SHA1 "git-\1"/' \
+			> git_sha1.h.tmp ; \
+		fi \
+	else \
+		cp $(srcdir)/git_sha1.h git_sha1.h.tmp ;\
+		chmod u+w git_sha1.h.tmp; \
+	fi
+
+git_sha1.h: git_sha1.h.tmp
+	@echo "updating git_sha1.h"
+	@if ! cmp -s git_sha1.h.tmp git_sha1.h; then \
+		mv git_sha1.h.tmp git_sha1.h ;\
+	else \
+		rm git_sha1.h.tmp ;\
+	fi
+
+BUILT_SOURCES = git_sha1.h
+
+# We want to keep the srcdir file since we need it on rebuild from tarball.
+# At the same time `make distclean' gets angry at us if we don't cleanup the
+# builddir one.
+distclean-local:
+	( test $(top_srcdir) != $(top_builddir) && rm $(builddir)/git_sha1.h ) || true
+
 SUBDIRS = . gtest util mapi/glapi/gen mapi
 
 # include only conditionally ?
 SUBDIRS += compiler
+
+if HAVE_INTEL_DRIVERS
+SUBDIRS += intel
+endif
 
 if NEED_OPENGL_COMMON
 SUBDIRS += mesa
@@ -34,16 +71,28 @@ if HAVE_DRI_GLX
 SUBDIRS += glx
 endif
 
-if HAVE_EGL_PLATFORM_WAYLAND
-SUBDIRS += egl/wayland/wayland-egl egl/wayland/wayland-drm
+## Optionally required by GBM and EGL
+if HAVE_PLATFORM_WAYLAND
+SUBDIRS += egl/wayland/wayland-drm
 endif
 
+## Optionally required by EGL (aka PLATFORM_GBM)
 if HAVE_GBM
 SUBDIRS += gbm
 endif
 
+## Optionally required by EGL
+if HAVE_PLATFORM_WAYLAND
+SUBDIRS += egl/wayland/wayland-egl
+endif
+
 if HAVE_EGL
 SUBDIRS += egl
+endif
+
+## Requires the i965 compiler (part of mesa) and wayland-drm
+if HAVE_INTEL_VULKAN
+SUBDIRS += intel/vulkan
 endif
 
 if HAVE_GALLIUM
@@ -51,7 +100,7 @@ SUBDIRS += gallium
 endif
 
 EXTRA_DIST = \
-	getopt hgl SConscript
+	getopt hgl SConscript git_sha1.h
 
 AM_CFLAGS = $(VISIBILITY_CFLAGS)
 AM_CXXFLAGS = $(VISIBILITY_CXXFLAGS)
