Updated following packages to latest git version:
xserver          commit f59871587ea678d4c498874895f4b97687764ee1
libxcb           commit 3c946010c8521497b0fba2c8bc9bde184622345a
libxcb/xcb-proto commit 1388374c7149114888a6a5cd6e9bf6ad4b42adf8
xkeyboard-config commit 3998ddde5bda96538fadd7de42a63f0b7c43d85d
libX11           commit c745719e23af44a4b40ab4508447637b35d91a1e
libXdmcp         commit fa41f9bfd7a0e57ba3e0f40d9a96e1dba1deeb4a
libXext          commit 6cb21433d745abea3a161a6fc8e141f7e08b2c27
libfontenc       commit 2408433404732b146bf41a2451d23ffadad5a816
libXinerama      commit 51c28095951676a5896437c4c3aa40fb1972bad2
libXau           commit f4fc44202b554e68093828b556f8c7fd9644ddb0
xkbcomp          commit ff32f542c94f1b30ba2ba58193adb3774a5c50e6
pixman           commit 7883ab8d637cbdf3b12bb17525616a5372de3d02
mkfontscale      commit b7ebb9b042974874782f4e662bfc442bc96c5647
xwininfo         commit ab427b9bfd495a7e9a5dc690f5abe5a2859b8de3
libXft           commit 4e4210c86019b42c3819cc18b59f86752fcd8b13
libXmu           commit 017d1deaf923887df74b068c33d080008b0c25cf
libxtrans        commit 806f04c6e4529358f160e53135baf105e4ecf3b8
fontconfig       commit 72b9a48f57de6204d99ce1c217b5609ee92ece9b
mesa             commit 55c262898ae7188311c89a60e4ec0fbb67b7a95b
putty            commit b846178443cf1a5dc7c5ea2079fd34fd465af497
pthreads         commit f12b445b336ee0117b43fca1d4b9f22c9af82c36
EGL-Registry     commit a03692eea13514d9aef01822b2bc6575fcabfac2
xorgproto        commit 1c8128d72df22843a2022576850bc5ab5e3a46ea

diff --git a/mesalib/.gitlab-ci/test/gitlab-ci.yml b/mesalib/.gitlab-ci/test/gitlab-ci.yml
--- a/mesalib/.gitlab-ci/test/gitlab-ci.yml
+++ b/mesalib/.gitlab-ci/test/gitlab-ci.yml
@@ -8,49 +8,128 @@
     # Note: Build dir (and thus install) may be dirty due to GIT_STRATEGY
     - rm -rf install
     - tar -xf artifacts/install.tar
-    - echo -e "\e[0Ksection_start:$(date +%s):ldd_section[collapsed=true]\r\e[0KChecking ldd on driver build"
+    - section_start ldd_section "Checking ldd on driver build"
     - LD_LIBRARY_PATH=install/lib find install/lib -name "*.so" -print -exec ldd {} \;
-    - echo -e "\e[0Ksection_end:$(date +%s):ldd_section\r\e[0K"
+    - section_end ldd_section
   artifacts:
     when: always
     name: "mesa_${CI_JOB_NAME}"
     paths:
       - results/
+  rules:
+    - !reference [.never-post-merge-rules, rules]
 
-rustfmt:
+.formatting-check:
   # Cancel job if a newer commit is pushed to the same branch
   interruptible: true
-  stage: lint
+  stage: code-validation
   extends:
-    - .use-debian/x86_build
-    - .lint-rustfmt-rules
+    - .use-debian/x86_64_build
   variables:
     GIT_STRATEGY: fetch
+  timeout: 10m
   script:
-    - git ls-files */{lib,app}.rs | xargs rustfmt --check
+    - git diff --color=always --exit-code  # Fails if there are diffs
+  tags:
+    - placeholder-job
+
+rustfmt:
+  extends:
+    - .formatting-check
+    - .lint-rustfmt-rules
+  before_script:
+    - shopt -s globstar
+    - rustfmt --version
+    - rustfmt --verbose src/**/lib.rs
+    - rustfmt --verbose src/**/main.rs
+
+clang-format:
+  extends:
+    - .formatting-check
+    - .lint-clang-format-rules
+  variables:
+    LLVM_VERSION: 15
+  before_script:
+    - shopt -s globstar
+    # We need a meson build dir, but its config doesn't actually matter, so
+    # let's just use the default.
+    - meson setup build
+    - clang-format-${LLVM_VERSION} --version
+    - ninja -C build clang-format
+
+.test-check:
+  # Cancel job if a newer commit is pushed to the same branch
+  interruptible: true
+  stage: code-validation
+  extends:
+    - .use-debian/x86_64_build
+  variables:
+    GIT_STRATEGY: fetch
+  timeout: 10m
+
+python-test:
+  extends:
+    - .test-check
+  script:
+    - cd bin/ci
+    - pip install --break-system-packages -r test/requirements.txt
+    - PYTHONPATH=. pytest -v
+  rules:
+    - !reference [.disable-farm-mr-rules, rules]
+    - !reference [.never-post-merge-rules, rules]
+    - changes:
+        - bin/ci/**/*
 
 .test-gl:
   extends:
     - .test
-    - .use-debian/x86_test-gl
+    - .use-debian/x86_64_test-gl
   needs:
-    - debian/x86_test-gl
+    - debian/x86_64_test-gl
     - debian-testing
+    - !reference [.required-for-hardware-jobs, needs]
+  variables:
+    DEBIAN_ARCH: amd64
 
 .test-vk:
   extends:
     - .test
-    - .use-debian/x86_test-vk
+    - .use-debian/x86_64_test-vk
   needs:
     - debian-testing
-    - debian/x86_test-vk
+    - debian/x86_64_test-vk
+    - !reference [.required-for-hardware-jobs, needs]
+  variables:
+    DEBIAN_ARCH: amd64
 
 .test-cl:
   extends:
     - .test
-    - .use-debian/x86_test-gl
+    - .use-debian/x86_64_test-gl
   needs:
-    - debian/x86_test-gl
+    - debian/x86_64_test-gl
+    - !reference [.required-for-hardware-jobs, needs]
+
+.test-android:
+  extends:
+    - .test
+    - .use-debian/x86_64_test-android
+  variables:
+    S3_ARTIFACT_NAME: mesa-x86_64-android-debug
+  needs:
+    - job: debian-testing
+      artifacts: true  # On the host we want the Linux build
+    - job: debian-android
+      artifacts: false  # The Android build will be downloaded later
+    - job: debian/x86_64_test-android
+      artifacts: false
+    - !reference [.required-for-hardware-jobs, needs]
+  timeout: 20m
+  script:
+    - ./install/cuttlefish-runner.sh
+  artifacts:
+    paths:
+      - results/
 
 .vkd3d-proton-test:
   artifacts:
@@ -87,15 +166,18 @@ rustfmt:
     exclude:
       - results/*.shader_cache
   variables:
-    PIGLIT_REPLAY_EXTRA_ARGS:  --keep-image --db-path ${CI_PROJECT_DIR}/replayer-db/ --minio_host=minio-packet.freedesktop.org --minio_bucket=mesa-tracie-public --role-session-name=${CI_PROJECT_PATH}:${CI_JOB_ID} --jwt-file=${CI_JOB_JWT_FILE}
+    PIGLIT_REPLAY_EXTRA_ARGS: --db-path ${CI_PROJECT_DIR}/replayer-db/ --minio_bucket=mesa-tracie-public --jwt-file=${CI_JOB_JWT_FILE}
+    # until we overcome Infrastructure issues, give traces extra 5 min before timeout
+    DEVICE_HANGING_TIMEOUT_SEC: 600
   script:
-    - echo -e "\e[0Ksection_start:$(date +%s):variables[collapsed=true]\r\e[0KVariables passed through:"
+    - section_start variables "Variables passed through:"
     - install/common/generate-env.sh
-    - echo -e "\e[0Ksection_end:$(date +%s):variables\r\e[0K"
+    - section_end variables
     - install/piglit/piglit-traces.sh
 
 .deqp-test:
   script:
+    - rm -rf results # Clear out old results if the docker container was cached
     - ./install/deqp-runner.sh
   artifacts:
     exclude:
@@ -108,11 +190,6 @@ rustfmt:
     - .deqp-test
   variables:
     DEQP_VER: vk
-
-.skqp-test:
-  variables:
-    HWCI_START_XORG: 1
-    HWCI_TEST_SCRIPT: "/install/skqp-runner.sh"
 
 .fossilize-test:
   script:
@@ -134,9 +211,13 @@ rustfmt:
     # instead of fd.o.  Set FDO_HTTP_CACHE_URI to an http cache for your test lab to
     # improve it even more (see https://docs.mesa3d.org/ci/bare-metal.html for
     # setup).
-    - echo -e "\e[0Ksection_start:$(date +%s):artifacts_download[collapsed=true]\r\e[0KDownloading artifacts from minio"
-    - wget ${FDO_HTTP_CACHE_URI:-}https://${PIPELINE_ARTIFACTS_BASE}/${MINIO_ARTIFACT_NAME}.tar.zst -S --progress=dot:giga -O- | tar --zstd -x
-    - echo -e "\e[0Ksection_end:$(date +%s):artifacts_download\r\e[0K"
+    - section_start artifacts_download "Downloading artifacts from s3"
+    # Note: Build dir (and thus install) may be dirty due to GIT_STRATEGY
+    - rm -rf install
+    - (set -x; curl -L --retry 4 -f --retry-all-errors --retry-delay 60 ${FDO_HTTP_CACHE_URI:-}https://${PIPELINE_ARTIFACTS_BASE}/${S3_ARTIFACT_NAME}.tar.zst | tar --zstd -x)
+    - section_end artifacts_download
+  variables:
+    BM_ROOTFS: /rootfs-${DEBIAN_ARCH}
   artifacts:
     when: always
     name: "mesa_${CI_JOB_NAME}"
@@ -149,43 +230,59 @@ rustfmt:
       junit: results/junit.xml
 
 # ARM testing of bare-metal boards attached to an x86 gitlab-runner system
-.baremetal-test-armhf:
+.baremetal-test-arm32:
   extends:
     - .baremetal-test
-    - .use-debian/arm_test
+    - .use-debian/arm32_test
   variables:
-    BM_ROOTFS: /rootfs-armhf
-    MINIO_ARTIFACT_NAME: mesa-armhf
+    DEBIAN_ARCH: armhf
+    S3_ARTIFACT_NAME: mesa-arm32-default-debugoptimized
   needs:
-    - debian/arm_test
-    - job: debian-armhf
+    - debian/arm32_test
+    - job: debian-arm32
       artifacts: false
+    - !reference [.required-for-hardware-jobs, needs]
 
 # ARM64 testing of bare-metal boards attached to an x86 gitlab-runner system
 .baremetal-test-arm64:
   extends:
     - .baremetal-test
-    - .use-debian/arm_test
+    - .use-debian/arm64_test
   variables:
-    BM_ROOTFS: /rootfs-arm64
-    MINIO_ARTIFACT_NAME: mesa-arm64
+    DEBIAN_ARCH: arm64
+    S3_ARTIFACT_NAME: mesa-arm64-default-debugoptimized
   needs:
-    - debian/arm_test
+    - debian/arm64_test
     - job: debian-arm64
       artifacts: false
+    - !reference [.required-for-hardware-jobs, needs]
 
-# ARM64 testing of bare-metal boards attached to an x86 gitlab-runner system, using an asan mesa build
+# ARM32/64 testing of bare-metal boards attached to an x86 gitlab-runner system, using an asan mesa build
+.baremetal-arm32-asan-test:
+  extends:
+    - .baremetal-test
+    - .use-debian/arm32_test
+  variables:
+    DEQP_RUNNER_OPTIONS: "--env LD_PRELOAD=libasan.so.8:/install/lib/libdlclose-skip.so"
+    S3_ARTIFACT_NAME: mesa-arm32-asan-debugoptimized
+  needs:
+    - debian/arm32_test
+    - job: debian-arm32-asan
+      artifacts: false
+    - !reference [.required-for-hardware-jobs, needs]
+
 .baremetal-arm64-asan-test:
   extends:
     - .baremetal-test
-    - .use-debian/arm_test
+    - .use-debian/arm64_test
   variables:
-    DEQP_RUNNER_OPTIONS: "--env LD_PRELOAD=libasan.so.6:/install/lib/libdlclose-skip.so"
-    MINIO_ARTIFACT_NAME: mesa-arm64-asan
+    DEQP_RUNNER_OPTIONS: "--env LD_PRELOAD=libasan.so.8:/install/lib/libdlclose-skip.so"
+    S3_ARTIFACT_NAME: mesa-arm64-asan-debugoptimized
   needs:
-    - debian/arm_test
+    - debian/arm64_test
     - job: debian-arm64-asan
       artifacts: false
+    - !reference [.required-for-hardware-jobs, needs]
 
 .baremetal-deqp-test:
   variables:
@@ -198,33 +295,37 @@ rustfmt:
   # image:, but the integration is not possible for the current
   # use-case. Within this job, two containers are managed. 1) the
   # gitlab runner container from which the job is submitted to the
-  # DUT, and 2) the test container (e.g. debian/x86_test-vk) within
+  # DUT, and 2) the test container (e.g. debian/x86_64_test-vk) within
   # which the test cases will run on the DUT. Since ci-templates and
   # the associated image setting macros in this file rely on variables
   # like FDO_DISTRIBUTION_TAG for *the* image, there is no way to
   # depend on more than one image per job. So, the job container is
   # built as part of the CI in the boot2container project.
-  image: registry.freedesktop.org/mupuf/valve-infra/mesa-trigger:2022-03-03.2
+  image: registry.freedesktop.org/gfx-ci/ci-tron/mesa-trigger:2023-06-02.1
   timeout: 1h 40m
+  rules:
+    - if: $FORCE_KERNEL_TAG != null
+      when: never
   variables:
     # No need by default to pull the whole repo
     GIT_STRATEGY: none
     # boot2container initrd configuration parameters.
-    B2C_KERNEL_URL: 'https://gitlab.freedesktop.org/mupuf/valve-infra/-/package_files/144/download'  # 5.17.1
-    B2C_INITRAMFS_URL: 'https://gitlab.freedesktop.org/mupuf/boot2container/-/releases/v0.9.8/downloads/initramfs.linux_amd64.cpio.xz'
+    B2C_KERNEL_URL: 'https://gitlab.freedesktop.org/gfx-ci/ci-tron/-/package_files/519/download'  # Linux 6.1
+    B2C_INITRAMFS_URL: 'https://gitlab.freedesktop.org/mupuf/boot2container/-/releases/v0.9.10/downloads/initramfs.linux_amd64.cpio.xz'
     B2C_JOB_SUCCESS_REGEX: '\[.*\]: Execution is over, pipeline status: 0\r$'
-    B2C_JOB_WARN_REGEX: '\*ERROR\* ring .* timeout, but soft recovered'
+    B2C_JOB_WARN_REGEX: '\*ERROR\* ring .* timeout'
     B2C_LOG_LEVEL: 6
     B2C_POWEROFF_DELAY: 15
     B2C_SESSION_END_REGEX: '^.*It''s now safe to turn off your computer\r$'
-    B2C_SESSION_REBOOT_REGEX: '(GPU hang detected!|\*ERROR\* ring [^\s]+ timeout(?!, but soft recovered)|The CS has been cancelled because the context is lost)'
+    B2C_SESSION_REBOOT_REGEX: ''
     B2C_TIMEOUT_BOOT_MINUTES: 45
-    B2C_TIMEOUT_BOOT_RETRIES: 1
-    B2C_TIMEOUT_FIRST_MINUTES: 5
+    B2C_TIMEOUT_BOOT_RETRIES: 0
+    B2C_TIMEOUT_FIRST_MINUTES: 2
     B2C_TIMEOUT_FIRST_RETRIES: 3
-    B2C_TIMEOUT_MINUTES: 2
+    B2C_TIMEOUT_MINUTES: 5
     B2C_TIMEOUT_OVERALL_MINUTES: 90
     B2C_TIMEOUT_RETRIES: 0
+    B2C_JOB_VOLUME_EXCLUSIONS: "*.shader_cache,install/*,*/install/*,*/vkd3d-proton.cache*,vkd3d-proton.cache*,*.qpa"
 
     # As noted in the top description, we make a distinction between the
     # container used by gitlab-runner to queue the work, and the container
@@ -236,14 +337,15 @@ rustfmt:
     INSTALL_TARBALL: "./artifacts/${INSTALL_TARBALL_NAME}"
     CI_B2C_ARTIFACTS: "./artifacts/b2c"
     CI_COMMON_SCRIPTS: "./artifacts/ci-common"
-    GENERATE_ENV_SCRIPT: "${CI_COMMON_SCRIPTS}/generate-env.sh"
     B2C_JOB_TEMPLATE: "${CI_B2C_ARTIFACTS}/b2c.yml.jinja2.jinja2"
     JOB_FOLDER: "job_folder"
+
   before_script:
     # We don't want the tarball unpacking of .test, but will take the JWT bits.
     - !reference [default, before_script]
+
     - |
-      set -x
+      set -eux
 
       # Useful as a hook point for runner admins. You may edit the
       # config.toml for the Gitlab runner and use a bind-mount to
@@ -264,48 +366,24 @@ rustfmt:
       [ -d "$CI_B2C_ARTIFACTS" ] || exit 1
       [ -d "$CI_COMMON_SCRIPTS" ] || exit 1
 
-
-      B2C_TEST_SCRIPT="bash -c 'source ./set-job-env-vars.sh; tar xf ${INSTALL_TARBALL_NAME}; ${B2C_TEST_SCRIPT}'"
+      export B2C_CONTAINER_CMD="bash -euc 'tar xf ${INSTALL_TARBALL_NAME}; ./install/common/init-stage2.sh'"
 
       # The Valve CI gateway receives jobs in a YAML format. Create a
       # job description from the CI environment.
-      python3 "$CI_B2C_ARTIFACTS"/generate_b2c.py \
-        --ci-job-id "${CI_JOB_ID}" \
-        --container-cmd "${B2C_TEST_SCRIPT}" \
-        --initramfs-url "${B2C_INITRAMFS_URL}" \
-        --job-success-regex "${B2C_JOB_SUCCESS_REGEX}" \
-        --job-warn-regex "${B2C_JOB_WARN_REGEX}" \
-        --kernel-url "${B2C_KERNEL_URL}" \
-        --log-level "${B2C_LOG_LEVEL}" \
-        --poweroff-delay "${B2C_POWEROFF_DELAY}" \
-        --session-end-regex "${B2C_SESSION_END_REGEX}" \
-        --session-reboot-regex "${B2C_SESSION_REBOOT_REGEX}" \
-        --tags "${CI_RUNNER_TAGS}" \
-        --template "${B2C_JOB_TEMPLATE}" \
-        --timeout-boot-minutes "${B2C_TIMEOUT_BOOT_MINUTES}" \
-        --timeout-boot-retries "${B2C_TIMEOUT_BOOT_RETRIES}" \
-        --timeout-first-minutes "${B2C_TIMEOUT_FIRST_MINUTES}" \
-        --timeout-first-retries "${B2C_TIMEOUT_FIRST_RETRIES}" \
-        --timeout-minutes "${B2C_TIMEOUT_MINUTES}" \
-        --timeout-overall-minutes "${B2C_TIMEOUT_OVERALL_MINUTES}" \
-        --timeout-retries "${B2C_TIMEOUT_RETRIES}" \
-        --job-volume-exclusions "${B2C_JOB_VOLUME_EXCLUSIONS}" \
-        --local-container "${IMAGE_UNDER_TEST}" \
-        ${B2C_EXTRA_VOLUME_ARGS} \
-        --working-dir "$CI_PROJECT_DIR"
+      python3 "$CI_B2C_ARTIFACTS"/generate_b2c.py
 
       cat b2c.yml.jinja2
 
       rm -rf ${JOB_FOLDER} || true
       mkdir -v ${JOB_FOLDER}
+
       # Create a script to regenerate the CI environment when this job
       # begins running on the remote DUT.
       set +x
       "$CI_COMMON_SCRIPTS"/generate-env.sh > ${JOB_FOLDER}/set-job-env-vars.sh
-      chmod +x ${JOB_FOLDER}/set-job-env-vars.sh
+      echo "export SCRIPTS_DIR=./install" >> ${JOB_FOLDER}/set-job-env-vars.sh
       echo "Variables passed through:"
       cat ${JOB_FOLDER}/set-job-env-vars.sh
-      echo "export CI_JOB_JWT=${CI_JOB_JWT}" >> ${JOB_FOLDER}/set-job-env-vars.sh
       set -x
 
       # Copy the mesa install tarball to the job folder, for later extraction
@@ -319,33 +397,40 @@ rustfmt:
       # Submit the job to Valve's CI gateway service with the CI
       # provisioned job_folder.
       env PYTHONUNBUFFERED=1 executorctl \
-          run -w b2c.yml.jinja2 -j $(slugify "$CI_JOB_NAME") -s ${JOB_FOLDER}
+          run -w b2c.yml.jinja2 -j $(slugify "$CI_JOB_NAME") -s ${JOB_FOLDER} -i "$CI_RUNNER_DESCRIPTION"
 
-      ls -l
-      # Anything our job places in results/ will be collected by the
-      # Gitlab coordinator for status presentation. results/junit.xml
-      # will be parsed by the UI for more detailed explanations of
-      # test execution.
+  # Anything our job places in results/ will be collected by the
+  # Gitlab coordinator for status presentation. results/junit.xml
+  # will be parsed by the UI for more detailed explanations of
+  # test execution.
+  after_script:
+    # Keep the results path the same as baremetal and LAVA
+    - mkdir -p "${JOB_FOLDER}"/results
+    - mv "${JOB_FOLDER}"/results results/
+    - !reference [default, after_script]
+
   artifacts:
     when: always
     name: "mesa_${CI_JOB_NAME}"
     paths:
-      - ${JOB_FOLDER}/results
+      - results
     reports:
-      junit: ${JOB_FOLDER}/results/junit.xml
+      junit: results/**/junit.xml
 
 .b2c-test-vk:
   extends:
-    - .use-debian/x86_test-vk
+    - .use-debian/x86_64_test-vk
     - .b2c-test
   needs:
-    - debian/x86_test-vk
+    - debian/x86_64_test-vk
     - debian-testing
+    - !reference [.required-for-hardware-jobs, needs]
 
 .b2c-test-gl:
   extends:
-    - .use-debian/x86_test-gl
+    - .use-debian/x86_64_test-gl
     - .b2c-test
   needs:
-    - debian/x86_test-gl
+    - debian/x86_64_test-gl
     - debian-testing
+    - !reference [.required-for-hardware-jobs, needs]
